version: '2'

services:
 db:
  build: db
  volumes:
   - data:/var/lib/mysql

 api:
  build: api
  links:
   - db

 web:
  build: web
 
 nginx:
  build: nginx
  ports:
   - "80:80"
  links:
   - api
   - web

volumes:
  data:
