version: '2'

services:
 db:
  build: db
  volumes:
   - data:/var/lib/mysql

 api:
  build: api
  links:
   - db

 web:
  build: 
   context: ./web
   dockerfile: Dockerfile-prod
  environment:
    NODE_ENV: production
 
 nginx:
  build: nginx
  ports:
   - "80:80"
  links:
   - api
   - web

volumes:
  data: